spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据源链接
    url: jdbc:mysql://mysql:3306/db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&verifyServerCertificate=false&tinyInt1isBit=false&serverTimezone=GMT%2B8
    #数据库用户名
    username: root
    #数据库密码
    password: 123456
    druid:
      #数据源最大链接数
      max-active: 50
  redis:
    host: redishost
    database: 8
    port: 6379
    password: 123456
  session:
    store-type: redis
    timeout: 14400  #以秒为单位
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      #单文件大小
      max-file-size:  100MB
      #一次请求文件的大小
      max-request-size: 100MB
  mvc:
    pathmatch:
      # 就这个来做后缀匹配，springboot2.x
      use-suffix-pattern: true
server:
  tomcat:
    max-swallow-size: 110MB
  #启动的web服务端口号
  port: 8080
  #servlet:
  #  context-path: /test
share:
  #规范配置，应用id，实施测试不要修改
  app-id: share
  #规范配置，模块id，实施测试不要修改
  module-id: java-coding-standard
  mapping:
    enabled: false
    public-module: /actuator,/public,/code,/api/,/rpc,/error,${management.context-path:}
  security-login:
    enabled: false
    password-encrypt: none
  code:
    # 没有做JDBC加载的表码，忽略dataLoader
    ignore-data-loader: true
    init-table: T_SYS_INIT_LOAD_TABLE
    redis-cache:
      enable: false
      name-space: ${share.app-id}-${share.module-id}
      database: 13
    enums:
      save-cache: false
      # 枚举对象扫描路径。
      scan-package: com.hyx.recordmoney.module.constant.enums

  file:
    fileServerType: base
    fileCenterServerPath: http://localhost:8888
    fileCenterFrontPath: /
    storage:
      type: JFS
      jfsPath: /home/files
      #DFS存储时用的，使用了JFS，此节点可以不配置
    #      dfs:
    #        serverIp: 192.168.0.235
    #        serverProxyIp: 192.168.0.235
    #        port: 1314
    #        localIp: 192.168.1.150
    manager:
      #存储信息管理，none、encrypt、table
      type: encrypt
    adapter:
      support-relative-name: true
      enable-common-fs: true
      enable-scurd: true
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/**/**.xml
  type-enums-package: com.hyx.recordmoney.module.constant.enums
debug: false
